import type { Metadata } from "next";
import { heading, sans } from "@/fonts";

import { Layout } from "@/components/structure/layout/layout";

import "@/styles/globals.css";
import { USE_LANDING } from "@/constants";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          async
          src={`https://widgets.givebutter.com/latest.umd.cjs?acct=fNIAQ0zJdp5wTemi&p=other`}
          id="givebutter-widget-script"
        />
      </head>
      <body className={`${sans.variable} ${heading.variable}  antialiased`}>
        {!USE_LANDING ? <Layout>{children}</Layout> : children}
      </body>
    </html>
  );
}
