import type { Metadata } from "next";
import { sans } from "@/fonts";

import { Layout } from "@/components/structure/layout/layout";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sans.variable}  antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
