import type { Metadata } from "next";
import { sans } from "@/fonts";

import { Layout } from "@/components/structure/layout/layout";

import "@/styles/globals.css";
import { USE_LANDING } from "@/constants";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sans.variable}  antialiased`}>
        {!USE_LANDING ? <Layout>{children}</Layout> : children}
      </body>
    </html>
  );
}
